### ISSUE TITLE
ethpm registry 

### ISSUE THREAD

**Issue by njgheorghita** [ethpm/ethpm-cli#30]
Create cli arg to help with managing registries. 

```shell
$ ethpm registry
```
Shows active registry address if set. And if private keys have ownership permission

```shell
$ ethpm registry --set 0x123abc
```
Sets active registry. If an active registry is already set, popup to confirm that you want to overwrite the old active registry with the new active registry.

```shell
$ ethpm registry list
```
List all available `package_name`s, `version`s and `uri`s available on the active registry

```shell
$ ethpm registry publish --package-name [PKG_NAME] --version [VERSION] --uri [URI]
```
Publish a package

In terms of key management, the current thought is to just require the user to set their private key as an environment variable `ETHPM_CLI_PRIVATE_KEY`. I'm definitely open to more secure approaches.

**Comment by pipermerriam** [comment]
Maybe instead of `--set`, 

```
$ ethpm registry add 0x1234 <optional alias>
```

New registries are added to the *end* of the list and are lower priority than registries added earlier.  The `ethpm registry list` command can then display the alias next to the address making the output easier to understand.
