### ISSUE TITLE
Set/get `ethpm_dir` as an environment variable

### ISSUE THREAD

**Issue by njgheorghita** [ethpm/ethpm-cli#37]
In pretty much every cli command, we have the optional argument for `ethpm_dir` which is a path to the target `_ethpm_packages` dir. This defaults to `./_ethpm_packages` if no argument is provided. Personally, I'd prefer to set this argument as an environment variable rather than worry about being in the correct working directory or manually input the argument over and over. However, there might be some unintended consequences to this strategy that I'm not aware of?

**Comment by njgheorghita** [comment]
ping @pipermerriam for any thoughts?

**Comment by pipermerriam** [comment]
:+1: for environment variable based ways to set proper defaults like this.  Keep the explicit CLI flag and ensure that the CLI flag takes precedence over the environment variable.
